@baseUrl = http://localhost:9200

####################################
############ INDEX #################
####################################

### create index customers
PUT {{baseUrl}}/customers

### create index products
PUT {{baseUrl}}/products

### create index orders
PUT {{baseUrl}}/orders

### show all indices
GET {{baseUrl}}/_cat/indices?v

### delete index customers
DELETE {{baseUrl}}/customers

### delete index products
DELETE {{baseUrl}}/products

### delete index orders
DELETE {{baseUrl}}/orders

### show all indices
GET {{baseUrl}}/_cat/indices?v


####################################
######## Dynamic Mapping ###########
####################################

### get customers mapping
GET {{baseUrl}}/customers/_mapping

### update customers mapping
PUT {{baseUrl}}/customers/_mapping
Content-Type: application/json

{
  "date_detection" : true,
  "dynamic_date_formats" : [
    "yyyy-MM-dd HH:mm:ss",
    "yyyy-MM-dd",
    "yyyy/MM/dd HH:mm:ss",
    "yyyy/MM/dd"
  ]
}

### update customers mapping
PUT {{baseUrl}}/customers/_mapping
Content-Type: application/json

{
  "numeric_detection": true
}

### get products mapping
GET {{baseUrl}}/products/_mapping

### update products mapping
PUT {{baseUrl}}/products/_mapping
Content-Type: application/json

{
  "date_detection" : true,
  "dynamic_date_formats" : [
    "yyyy-MM-dd HH:mm:ss",
    "yyyy-MM-dd",
    "yyyy/MM/dd HH:mm:ss",
    "yyyy/MM/dd"
  ]
}

### update products mapping
PUT {{baseUrl}}/products/_mapping
Content-Type: application/json

{
  "numeric_detection" : true
}

### get orders mapping
GET {{baseUrl}}/orders/_mapping

### update orders mapping
PUT {{baseUrl}}/orders/_mapping
Content-Type: application/json

{
  "date_detection" : true,
  "dynamic_date_formats" : [
    "yyyy-MM-dd HH:mm:ss",
    "yyyy-MM-dd",
    "yyyy/MM/dd HH:mm:ss",
    "yyyy/MM/dd"
  ]
}

### update orders mapping
PUT {{baseUrl}}/orders/_mapping
Content-Type: application/json

{
  "numeric_detection" : true
}


####################################
########### Create API #############
####################################

### create new customer
POST {{baseUrl}}/customers/_create/khannedy
Content-Type: application/json

{
  "name" : "Eko Kurniawan Khannedy",
  "register_at" : "2023-10-10 00:00:00"
}

### get customers mapping
GET {{baseUrl}}/customers/_mapping

### create product 1
POST {{baseUrl}}/products/_create/1
Content-Type: application/json

{
  "name" : "Indomie Ayam Bawang",
  "price" : "2000"
}

### create product 2
POST {{baseUrl}}/products/_create/2
Content-Type: application/json

{
  "name" : "Mie Sedap Soto",
  "price" : 2000
}

### get products mapping
GET {{baseUrl}}/products/_mapping

### create order 1
POST {{baseUrl}}/orders/_create/1
Content-Type: application/json

{
  "order_date": "2023-09-09 00:00:00",
  "customer_id": "khannedy",
  "total": "8000",
  "items": [
    {
      "product_id": "1",
      "price": "2000",
      "quantity": "2"
    },
    {
      "product_id": "2",
      "price": "2000",
      "quantity": "2"
    }
  ]
}

### get orders mapping
GET {{baseUrl}}/orders/_mapping


####################################
######### Get API ##################
####################################

### get customer khannedy
GET {{baseUrl}}/customers/_doc/khannedy

### get customer notfound
GET {{baseUrl}}/customers/_doc/salah

### get customer khannedy
GET {{baseUrl}}/customers/_source/khannedy

### get customer notfound
GET {{baseUrl}}/customers/_source/salah

### check customer khannedy
HEAD {{baseUrl}}/customers/_doc/khannedy

### check customer notfound
HEAD {{baseUrl}}/customers/_doc/salah


####################################
####### Multi Get API ##############
####################################

### get products 1 and 2
GET {{baseUrl}}/products/_mget
Content-Type: application/json

{
  "ids" : [
    "1", "2"
  ]
}

### get order 1 and customer khannedy
GET {{baseUrl}}/_mget
Content-Type: application/json

{
  "docs": [
    {
      "_id" : "1",
      "_index": "orders"
    },
    {
      "_id" : "khannedy",
      "_index": "customers"
    },
    {
      "_id" : "3",
      "_index": "products"
    }
  ]
}


####################################
######### Search API ###############
####################################

### search all products
POST {{baseUrl}}/products/_search

### search all products page 1
POST {{baseUrl}}/products/_search?size=1&from=0

### search all products page 2
POST {{baseUrl}}/products/_search?size=1&from=1

### search all products sort by price
POST {{baseUrl}}/products/_search?sort=price:asc

### search all products sort by name
POST {{baseUrl}}/products/_search?sort=name:desc


####################################
######## Index API #################
####################################

### create product 3
POST {{baseUrl}}/products/_doc/3
Content-Type: application/json

{
    "name": "Pop Mie Rasa Bakso",
    "price": 2500
}

### create product 4
POST {{baseUrl}}/products/_doc/4
Content-Type: application/json

{
    "name": "Sarimi isi 2",
    "price": 3000
}

### create product 5
POST {{baseUrl}}/products/_doc/5
Content-Type: application/json

{
    "name": "Mie Ayam",
    "price": 10000
}

### search all products
POST {{baseUrl}}/products/_search


####################################
############ Update API ############
####################################

### update price for product 5
POST {{baseUrl}}/products/_update/5
Content-Type: application/json

{
    "doc": {
        "price": 20000
    }
}


####################################
############ Delete API ############
####################################

### insert customer spammer
POST {{baseUrl}}/customers/_create/spammer
Content-Type: application/json

{
    "name": "spammer",
    "register_at": "2024-03-04 00:00:00"
}

### delete customer spammer
DELETE {{baseUrl}}/customers/_doc/spammer


####################################
############ Bulk API ##############
####################################

### search index
GET {{baseUrl}}/customers/_search

#### BUlk API
POST {{baseUrl}}/_bulk
Content-Type: application/x-ndjson

{"create" : {"_index" : "customers", "_id" : "Joko"}}
{"name" : "Jokowi Doodo", "register_at" : "2030-05-03 00:00:00"}
{"index" : {"_index" : "customers", "_id" : "budi"}}
{"name" : "Budi Nugraha", "register_at" : "2030-05-06 00:00:00"}
{"update" : {"_index" : "products", "_id" : "1"}}
{"doc" : {"price" : 4000}}
{"create" :  {"_index" : "customers", "_id" : "spammer"}}
{"name" : "Spammer", "register_at" : "2020-02-06 00:00:00"}
{"delete" : {"_index" : "customers", "_id" : "spammer"}}

###
#

####################################
########### Alias API ##############
####################################

### create alias customer and order
POST {{baseUrl}}/_aliases
Content-Type: application/json

{
  "actions" : [
    {
      "add" : {
        "alias" : "customer",
        "index" : "customers"
      }
    },
    {
      "add" : {
        "alias" : "order",
        "index" : "orders"
      }
    }
  ]
}

### get aliases
GET {{baseUrl}}/_aliases

### search index
GET {{baseUrl}}/customer/_search

### search index
GET {{baseUrl}}/order/_search


####################################
######### Reindex API ##############
####################################

### Create Index orders_v2
PUT {{baseUrl}}/orders_v2

### Mapping index orders_v2
PUT {{baseUrl}}/orders_v2/_mapping
Content-Type: application/json

{
  "date_detection" : true,
  "dynamic_date_formats" : [
    "yyyy-MM-dd HH:mm:ss",
    "yyyy-MM-dd",
    "yyyy/MM/dd HH:mm:ss",
    "yyyy/MM/dd"
  ]
}

### rindex index order to orders_v2
POST {{baseUrl}}/_reindex
Content-Type: application/json

{
  "source" : {
    "index" : "orders"
  },
  "dest" : {
    "index" : "orders_v2"
  }
}

### search index orders_v2
GET {{baseUrl}}/orders_v2/_search

### search index orders
GET {{baseUrl}}/orders/_search

### switch alias order from orders to orders_V2
POST {{baseUrl}}/_aliases
Content-Type: application/json

{
  "actions" : [
    {
      "remove": {
        "alias" : "order",
        "index" : "orders"
      }
    },
    {
      "add" : {
        "alias" : "order",
        "index" : "orders_v2"
      }
    }
  ]
}

### GET orders_v2 aliases
GET {{baseUrl}}/_aliases

### Search to order_v2 aliases
GET {{baseUrl}}/order/_search


####################################
############# Source  ##############
####################################

### seperti select total, customer_id, items, product from orders
GET {{baseUrl}}/order/_search?_source_includes=total,costomer_id,items.product_id

### select * except price from products
GET {{baseUrl}}/order/_search?_source_excludes=price

### select total,customer_id,items,products from orders where id = 1
GET {{baseUrl}}/order/_doc/1?_source_includes=total,customer_id,items.product_id


####################################
############# Mapping ##############
####################################

### create index customers_v2
PUT {{baseUrl}}/customers_v2
Content-Type: application/json


### update mapping customer_v2
PUT {{baseUrl}}/customers_v2/_mapping
Content-Type: application/json

{
  "numeric_detection": true,
  "date_detection" : true,
  "dynamic_date_formats" : [
    "yyyy-MM-dd HH:mm:ss",
    "yyyy-MM-dd",
    "yyyy/MM/dd HH:mm:ss",
    "yyyy/MM/dd"
  ],
  "properties": {
      "username": {
        "type": "keyword"
      },
      "first_name": {
        "type": "text"
      },
      "last_name": {
        "type": "text"
      },
      "email": {
        "type": "keyword"
      },
      "gender": {
        "type": "keyword"
      },
      "birth_date": {
        "type": "date",
        "format": "yyyy-MM-dd"
      }
  }
}

### get customers_v2
GET {{baseUrl}}/customers_v2

### switch alias customer from customers to customers_v2
POST {{baseUrl}}/_aliases
Content-Type: application/json

{
  "actions": [
    {
      "remove": {
        "alias": "customer",
        "index": "customers"
      }
    },
    {
      "add" : {
        "alias" : "customer",
        "index" : "customers_v2"
      }
    }
  ]
}

### get aliases customers_v2
GET {{baseUrl}}/_aliases

### search csutomer
GET {{baseUrl}}/customer/_search

### bulk insert customer
POST {{baseUrl}}/_bulk
Content-Type: application/json

< customers.json


####################################
############ Object Field ##########
####################################

### update customers_v2 mapping
PUT {{baseUrl}}/customers_v2/_mapping
Content-Type: application/json

{
  "properties": {
    "address": {
      "properties": {
        "street": {
          "type": "text"
        },
        "city": {
          "type": "text"
        },
        "province": {
          "type": "text"
        },
        "country": {
          "type": "text"
        },
        "zip_code": {
          "type": "keyword"
        }
      }
    }
  }
}

### update mapping customer_v2
GET {{baseUrl}}/customers_v2/_mapping

### INSERT customer
POST {{baseUrl}}/_bulk
Content-Type: application/json

< customers-with-address.json


####################################
############ Array Field ###########
####################################

### update customers_v2 mapping
PUT {{baseUrl}}/customers_v2/_mapping
Content-Type: application/json

{
  "properties": {
    "hobbies": {
      "type": "text"
    },
    "banks": {
      "properties": {
        "name": {
          "type": "text"
        },
        "account_number": {
          "type": "keyword"
        }
      }
    }
  }
}

### get customers_v2 mapping
GET {{baseUrl}}/customers_v2/_mapping

### bulk index customers_v2
POST {{baseUrl}}/_bulk
Content-Type: application/json

< customers-with-hobbies-and-banks.json

### search customer
POST {{baseUrl}}/customer/_search

####################################
############ Query #################
####################################

### search customer using match_all
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

### search customer using pagination
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "size": 5,
  "from": 0,
  "sort": [
    {
      "username": {
        "order": "desc"
      }
    }
  ]
}


####################################
############ Term Query ############
####################################

### search customer where gender = 'Female'
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "term": {
      "gender": "Female"
    }
  },
  "size": 5,
  "from": 0,
  "sort": [
    {
      "username": {
        "order": "desc"
      }
    }
  ]
}

### search customer where gender = 'BCA' # kosong karena tipedatanya text
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "term": {
      "banks.name": "BCA"
    }
  },
  "size": 5,
  "from": 0,
  "sort": [
    {
      "username": {
        "order": "desc"
      }
    }
  ]
}

####################################
############ Match Query ###########
####################################

### search customer where banks.name = 'BCA
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "banks.name": "BCA"
    }
  },
  "size": 5,
  "from": 0,
  "sort": [
    {
      "username": {
        "order": "desc"
      }
    }
  ]
}

### banks.name = "BCA" => banks.name = ["bca"]
### banks.name = "BCA Digital" => banks.name = ["bca", "digital"]
### email = "RIZKY@mail.com" => email = ["rizky", "mail", "com"]

### search customer where banks.name = 'BCA DIGITAL'
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "banks.name": {
        "query" : "BCA DIGITAL",
        "operator": "AND"
      }
    }
  },
  "size": 5,
  "from": 0,
  "sort": [
    {
      "username": {
        "order": "desc"
      }
    }
  ]
}


####################################
########### Terms Query ############
####################################

### search customer where username IN = ('username1', 'username2', 'username3')
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "terms": {
      "username": [
        "username1",
        "username2",
        "username3"
      ]
    }
  }
}

### search customer where banks.name IN = ('BCA', 'BNI', 'BTN')
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "terms": {
      "banks.name": [
        "bca",
        "btn",
        "bni"
      ]
    }
  }
}


####################################
######### Boolean Query ############
####################################

### MUST => search customer where hobbies = 'gaming' AND banks.name = 'bca'
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "hobbies": "gaming"
          }
        },
        {
          "match": {
            "banks.name": {
              "query": "bca digital",
              "operator": "AND"
            }
          }
        }
      ]
    }
  }
}

### FILTER => search customer where hobbies = 'gaming' AND banks.name = 'bca' (tanpa score)
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "hobbies": "gaming"
          }
        },
        {
          "match": {
            "banks.name": {
              "query": "bca digital",
              "operator": "AND"
            }
          }
        }
      ]
    }
  },
  "sort": [
    {
      "username": {
        "order": "desc"
      }
    }
  ]
}

### MUST NOT => search customer where hobbies != 'gaming' AND banks.name != 'bca'
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must_not": [
        {
          "term": {
            "hobbies": "gaming"
          }
        },
        {
          "match": {
            "banks.name": {
              "query": "bca digital",
              "operator": "AND"
            }
          }
        }
      ]
    }
  }
}

### SHOULD => search customer where hobbies = 'bni' OR banks.name = 'bca'
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "banks.name": "bni"
          }
        },
        {
          "term": {
            "banks.name": "bca"
          }
        }
      ]
    }
  }
}

### MUST & SHOULD => kalau begini, minimum shouldnya jadi tidak wajib
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "size": 10,
  "from": 315,
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "hobbies": "gaming"
          }
        }
      ],
      "should": [
        {
          "term": {
            "banks.name": "bni"
          }
        },
        {
          "term": {
            "banks.name": "bca"
          }
        }
      ]
    }
  }
}

### MUST & SHOULD with minimum SHOULD
POST {{baseUrl}}/customer/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "hobbies": "gaming"
          }
        }
      ],
      "should": [
        {
          "term": {
            "banks.name": "bni"
          }
        },
        {
          "term": {
            "banks.name": "bca"
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}